version: '3'
services:
  nodejs:
    build: ./nodejs

  scala:
    build: ./scala

  ethereum:
    build: ./ethereum
    depends_on:
      - ethereum-network
  ethereum-network:
    image: trufflesuite/ganache-cli:v6.0.3

  react:
    build: ./react

  react-native:
    build: ./react-native
