version: '3'
services:
  nodejs:
    volumes:
      - ./nodejs:/code
      - /code/node_modules

  scala:
    volumes:
      - ./scala:/code

  ethereum:
    volumes:
      - ./ethereum:/code
      - /code/node_modules

  react:
    command: ["npm", "run", "start:watch"]
    ports:
      - "8080:8080"
    volumes:
      - ./react:/code
      - /code/node_modules
