version: '3'
services:
  nodejs:
    command: ["npm", "run", "start-watch"]
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs:/code
      - /code/node_modules
  ethereum:
    depends_on:
      - ethereum-network
    volumes:
      - ./ethereum:/code
      - /code/node_modules
  ethereum-network:
    image: trufflesuite/ganache-cli:v6.0.3
