version: '3'
services:
  nodejs:
    command: ["npm", "run", "start-watch"]
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs:/code
      - /code/node_modules

  scala:
    volumes:
      - ./scala:/code

  ethereum:
    volumes:
      - ./ethereum:/code
      - /code/node_modules
