version: 2
jobs:
  build:
    working_directory: /code
    docker:
      - image: tmaier/docker-compose:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose build
      - run: docker-compose -f docker-compose.yml run --rm nodejs npm run test:acceptance
