---
- hosts: localhost
  vars:
    devel_user: devel
    nodejs_major_version: 8
  roles:
    - role: user_environment
      username: "{{ devel_user }}"

    - role: nodejs_install
      major_version: "{{ nodejs_major_version }}"
